#!/usr/bin/env node
// Build a self-contained Bun binary of the Orca DAG viewer.
//
//   node scripts/build-binary.mjs
//
// Steps:
//   1. `vite build`  → web/dist
//   2. embed web/dist as a base64 map in server/src/generated/webAssets.ts
//   3. `bun build --compile` → dist/orca-dag (bundles the viewer server + assets)
//
// The produced binary is portable: run it in ANY project directory and it uses
// that directory as the workspace. It needs only the `orca` CLI on PATH — the
// planning "brain" lives in your own agent via the orca-dag skill, so the
// viewer no longer embeds or requires the Claude Agent SDK.
//
// Cross-compile for another OS/arch by passing a Bun target, e.g.:
//   TARGET=bun-linux-x64  node scripts/build-binary.mjs
//   TARGET=bun-windows-x64 node scripts/build-binary.mjs
// (the target machine still needs its own `claude` + `orca` on PATH).

import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, extname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const distWeb = join(root, "web", "dist");
const genDir = join(root, "server", "src", "generated");
const genFile = join(genDir, "webAssets.ts");
const outDir = join(root, "dist");
const outName = process.env.OUT_NAME ?? "orca-dag";
const outFile = join(outDir, outName);
const target = process.env.TARGET; // optional Bun --target for cross-compile

const MIME = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".map": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".webp": "image/webp",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".txt": "text/plain; charset=utf-8",
  ".wasm": "application/wasm",
};

function run(cmd, args, opts = {}) {
  console.log(`\n$ ${cmd} ${args.join(" ")}`);
  execFileSync(cmd, args, { cwd: root, stdio: "inherit", ...opts });
}

function walk(dir) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const abs = join(dir, entry);
    if (statSync(abs).isDirectory()) out.push(...walk(abs));
    else out.push(abs);
  }
  return out;
}

// 1. Build the web app ------------------------------------------------------
run("npm", ["run", "build", "-w", "web"]);
if (!existsSync(distWeb)) throw new Error(`vite build produced no ${distWeb}`);

// 2. Embed web/dist ---------------------------------------------------------
const files = walk(distWeb);
let totalBytes = 0;
const entries = files.map((abs) => {
  const rel = relative(distWeb, abs).split(/[\\/]/).join("/"); // POSIX keys
  const buf = readFileSync(abs);
  totalBytes += buf.length;
  const type = MIME[extname(rel).toLowerCase()] ?? "application/octet-stream";
  return `  ${JSON.stringify(rel)}: { type: ${JSON.stringify(type)}, body: ${JSON.stringify(buf.toString("base64"))} },`;
});

mkdirSync(genDir, { recursive: true });
writeFileSync(
  genFile,
  `// AUTO-GENERATED by scripts/build-binary.mjs — do not edit, do not commit.\n` +
    `// ${files.length} files, ${(totalBytes / 1024).toFixed(0)} KiB from web/dist embedded as base64.\n` +
    `import type { EmbeddedAsset } from "../webAssets";\n\n` +
    `export const WEB_ASSETS: Record<string, EmbeddedAsset> = {\n${entries.join("\n")}\n};\n`,
);
console.log(`\nEmbedded ${files.length} web files (${(totalBytes / 1024).toFixed(0)} KiB) → ${relative(root, genFile)}`);

// 3. Compile the binary -----------------------------------------------------
mkdirSync(outDir, { recursive: true });
const buildArgs = ["build", "--compile", "server/src/index.ts", "--outfile", outFile];
if (target) buildArgs.push(`--target=${target}`);
try {
  run("bun", buildArgs);
} finally {
  // The generated module is a build artifact; don't leave it in the source tree.
  rmSync(genDir, { recursive: true, force: true });
}

const finalPath = existsSync(outFile) ? outFile : `${outFile}.exe`;
const sizeMB = (statSync(finalPath).size / (1024 * 1024)).toFixed(0);
console.log(`\n✅ Built ${relative(root, finalPath)} (${sizeMB} MB)`);
console.log(`   Install globally, then run inside any project:`);
console.log(`     cp ${relative(root, finalPath)} /usr/local/bin/orca-dag && cd ~/some/project && orca-dag`);
console.log(`   It serves http://localhost:8787 and uses that project dir as the workspace.`);
